/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; sets the refresh_token httpOnly cookie */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate tokens using the refresh_token cookie (no request body) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token and clear the cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile + roles */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (never includes passwordHash) */
        get: operations["UsersController_list"];
        put?: never;
        /** Create a user with a generated username and initial roles */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace a user's roles */
        patch: operations["UsersController_setRoles"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["RolesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trucks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trucks (optionally filtered by status) */
        get: operations["FleetController_list"];
        put?: never;
        /** Create a truck */
        post: operations["FleetController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trucks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a truck by id */
        get: operations["FleetController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a truck */
        patch: operations["FleetController_update"];
        trace?: never;
    };
    "/trucks/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Soft-deactivate a truck (status → inactive) */
        patch: operations["FleetController_deactivate"];
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workers (filter by status/type) */
        get: operations["WorkforceController_list"];
        put?: never;
        /** Create a worker */
        post: operations["WorkforceController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a worker by id */
        get: operations["WorkforceController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a worker */
        patch: operations["WorkforceController_update"];
        trace?: never;
    };
    "/workers/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Soft-deactivate a worker (status → disabled) */
        patch: operations["WorkforceController_deactivate"];
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clients (optionally filtered by status) */
        get: operations["ClientsController_list"];
        put?: never;
        /** Create a client */
        post: operations["ClientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a client by id */
        get: operations["ClientsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a client */
        patch: operations["ClientsController_update"];
        trace?: never;
    };
    "/clients/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Soft-deactivate a client (status → disabled) */
        patch: operations["ClientsController_deactivate"];
        trace?: never;
    };
    "/clients/{clientId}/rate-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a client's rate cards */
        get: operations["PricingController_listRateCards"];
        put?: never;
        /** Create a rate card under a client */
        post: operations["PricingController_createRateCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate-cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rate card by id */
        get: operations["PricingController_getRateCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a rate card */
        patch: operations["PricingController_updateRateCard"];
        trace?: never;
    };
    "/rate-cards/{cardId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Soft-deactivate a rate card (status → disabled) */
        patch: operations["PricingController_deactivateRateCard"];
        trace?: never;
    };
    "/rate-cards/{cardId}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a rate card's rates */
        get: operations["PricingController_listRates"];
        put?: never;
        /** Create a rate under a rate card */
        post: operations["PricingController_createRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the rate effective now for a client (trip prepopulation)
         * @description Returns { found, rate }. Money fields are stripped for ops roles by the global financial gate; they still receive { found, rate } and type the figures manually.
         */
        get: operations["PricingController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/{rateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a rate */
        patch: operations["PricingController_updateRate"];
        trace?: never;
    };
    "/rates/{rateId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Close a rate (set effectiveTo = now; non-destructive delete) */
        patch: operations["PricingController_closeRate"];
        trace?: never;
    };
    "/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-truck log status for a date + fleet roll-up counts */
        get: operations["OperationsController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the daily log for a (date, truckId) — 404 if none yet */
        get: operations["OperationsController_getLog"];
        put?: never;
        /** Get-or-create the daily log for a (date, truckId) */
        post: operations["OperationsController_createLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a daily log (with trips + derived totals) */
        get: operations["OperationsController_getLogById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a daily log (fuel, odometer, notes) */
        patch: operations["OperationsController_updateLog"];
        trace?: never;
    };
    "/daily-logs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm a daily log (draft → confirmed) */
        patch: operations["OperationsController_confirmLog"];
        trace?: never;
    };
    "/daily-logs/{id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a trip to a daily log (rate-prepopulated, editable) */
        post: operations["OperationsController_createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a trip (hard delete; ops_manager/finance/admin only) */
        delete: operations["OperationsController_deleteTrip"];
        options?: never;
        head?: never;
        /** Update a trip */
        patch: operations["OperationsController_updateTrip"];
        trace?: never;
    };
    "/reports/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip counts per day and per truck for a range */
        get: operations["ReportingController_trips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active-truck utilization per day for a range */
        get: operations["ReportingController_utilization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/worker-pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total driver + helper pay per worker (financial) */
        get: operations["ReportingController_workerPay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/client-billables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total billable per client (financial) */
        get: operations["ReportingController_clientBillables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Generated username
             * @example admin
             */
            username: string;
            /**
             * @description Plain password (verified against argon2 hash)
             * @example admin123
             */
            password: string;
        };
        AccessTokenResponseDto: {
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * @description Access-token lifetime in seconds
             * @example 900
             */
            expiresIn: number;
        };
        MeResponseDto: {
            id: string;
            username: string;
            /**
             * @description UI locale: en | es
             * @example en
             */
            locale: string;
            roles: ("admin" | "finance" | "ops_manager" | "ops_staff" | "driver" | "investor")[];
        };
        CreateUserDto: {
            /**
             * @description Full name; the username is generated from it.
             * @example Mario Gomez
             */
            fullName: string;
            /** @example mario@example.com */
            email?: string;
            /** @example +50760000000 */
            phone?: string;
            /**
             * @description Initial password (argon2-hashed; never stored in plaintext).
             * @example initial-password-123
             */
            password: string;
            /**
             * @description Role keys to assign on creation (at least one).
             * @example [
             *       "ops_staff"
             *     ]
             */
            roles: ("admin" | "finance" | "ops_manager" | "ops_staff" | "driver" | "investor")[];
            /**
             * @description UI locale.
             * @example en
             * @enum {string}
             */
            locale?: "en" | "es";
        };
        UserResponseDto: {
            id: string;
            /**
             * @description Generated username (firstInitial+lastName).
             * @example mgomez
             */
            username: string;
            email?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            /** @example en */
            locale: string;
            /** @enum {string} */
            status: "active" | "disabled";
            roles: ("admin" | "finance" | "ops_manager" | "ops_staff" | "driver" | "investor")[];
            /** Format: date-time */
            createdAt: string;
        };
        SetRolesDto: {
            /**
             * @description Replaces the user's roles with exactly this set.
             * @example [
             *       "ops_manager",
             *       "finance"
             *     ]
             */
            roles: ("admin" | "finance" | "ops_manager" | "ops_staff" | "driver" | "investor")[];
        };
        RoleResponseDto: {
            id: string;
            /** @enum {string} */
            key: "admin" | "finance" | "ops_manager" | "ops_staff" | "driver" | "investor";
            /** @example Operations Manager */
            name: string;
        };
        CreateTruckDto: {
            /**
             * @description Unique human-facing code/name for the truck.
             * @example Camión 7
             */
            code: string;
            /** @example PA-1234 */
            plate?: string;
            /** @example 2019 */
            year?: number;
            /**
             * @description Box length (ft).
             * @example 24
             */
            sizeFt?: number;
            /**
             * Format: date
             * @example 2019-03-15
             */
            purchaseDate?: string;
            /**
             * @description Acquisition cost (financial — stripped for ops roles).
             * @example 45000
             */
            purchasePrice?: number;
            /** @example 120000 */
            odometerStart?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        TruckResponseDto: {
            id: string;
            /** @example Camión 7 */
            code: string;
            plate?: Record<string, never> | null;
            year?: Record<string, never> | null;
            sizeFt?: Record<string, never> | null;
            purchaseDate?: Record<string, never> | null;
            /** @description Financial — absent in responses to ops roles. */
            purchasePrice?: Record<string, never> | null;
            odometerStart?: Record<string, never> | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateTruckDto: {
            /**
             * @description Unique human-facing code/name for the truck.
             * @example Camión 7
             */
            code?: string;
            /** @example PA-1234 */
            plate?: string;
            /** @example 2019 */
            year?: number;
            /**
             * @description Box length (ft).
             * @example 24
             */
            sizeFt?: number;
            /**
             * Format: date
             * @example 2019-03-15
             */
            purchaseDate?: string;
            /**
             * @description Acquisition cost (financial — stripped for ops roles).
             * @example 45000
             */
            purchasePrice?: number;
            /** @example 120000 */
            odometerStart?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        CreateWorkerDto: {
            /** @example Juan Pérez */
            fullName: string;
            /**
             * @default contractor
             * @enum {string}
             */
            type: "employee" | "contractor";
            /**
             * @description Can be assigned as a driver.
             * @default true
             */
            canDrive: boolean;
            /**
             * @description Can be assigned as a helper.
             * @default true
             */
            canHelp: boolean;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /** @description Optional link to a User account (future driver login). */
            userId?: string;
        };
        WorkerResponseDto: {
            id: string;
            /** @example Juan Pérez */
            fullName: string;
            /** @enum {string} */
            type: "employee" | "contractor";
            canDrive: boolean;
            canHelp: boolean;
            /** @enum {string} */
            status: "active" | "disabled";
            userId?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateWorkerDto: {
            /** @example Juan Pérez */
            fullName?: string;
            /**
             * @default contractor
             * @enum {string}
             */
            type: "employee" | "contractor";
            /**
             * @description Can be assigned as a driver.
             * @default true
             */
            canDrive: boolean;
            /**
             * @description Can be assigned as a helper.
             * @default true
             */
            canHelp: boolean;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /** @description Optional link to a User account (future driver login). */
            userId?: string;
        };
        CreateClientDto: {
            /** @example Distribuidora La Selva */
            name: string;
            /**
             * @description Optional unique short code.
             * @example SELVA
             */
            code?: string;
            /**
             * @description Free-text billing cadence hint (periods are client-driven).
             * @example monthly
             */
            billingFrequency?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        ClientResponseDto: {
            id: string;
            /** @example Distribuidora La Selva */
            name: string;
            code?: Record<string, never> | null;
            billingFrequency?: Record<string, never> | null;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateClientDto: {
            /** @example Distribuidora La Selva */
            name?: string;
            /**
             * @description Optional unique short code.
             * @example SELVA
             */
            code?: string;
            /**
             * @description Free-text billing cadence hint (periods are client-driven).
             * @example monthly
             */
            billingFrequency?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        CreateRateCardDto: {
            /**
             * @description Rate card label.
             * @example Standard 2026
             */
            name: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        RateCardResponseDto: {
            id: string;
            clientId: string;
            /** @example Standard 2026 */
            name: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
        };
        UpdateRateCardDto: {
            /**
             * @description Rate card label.
             * @example Standard 2026
             */
            name?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        CreateRateDto: {
            /**
             * @description Route/service label used by the trip-prepopulation lookup.
             * @example Ciudad → Colón
             */
            label?: string;
            /**
             * @description Price charged to the client.
             * @example 350
             */
            clientPrice: number;
            /**
             * @description Driver pay for this rate.
             * @example 120
             */
            driverPay: number;
            /**
             * @description Helper pay for this rate.
             * @example 60
             */
            helperPay: number;
            /**
             * Format: date-time
             * @description When this rate becomes effective (defaults to now).
             */
            effectiveFrom?: string;
            /**
             * Format: date-time
             * @description When this rate stops being effective (null = open-ended).
             */
            effectiveTo?: string;
        };
        RateResponseDto: {
            id: string;
            rateCardId: string;
            /** @example Ciudad → Colón */
            label?: Record<string, never> | null;
            /** @description Financial — absent for ops roles. */
            clientPrice: string;
            /** @description Financial — absent for ops roles. */
            driverPay: string;
            /** @description Financial — absent for ops roles. */
            helperPay: string;
            /** Format: date-time */
            effectiveFrom: string;
            effectiveTo?: Record<string, never> | null;
        };
        RateLookupResponseDto: {
            /** @description Whether an effective rate was found. */
            found: boolean;
            /** @description The effective rate, or null when none applies. */
            rate?: components["schemas"]["RateResponseDto"] | null;
        };
        UpdateRateDto: {
            /**
             * @description Route/service label used by the trip-prepopulation lookup.
             * @example Ciudad → Colón
             */
            label?: string;
            /**
             * @description Price charged to the client.
             * @example 350
             */
            clientPrice?: number;
            /**
             * @description Driver pay for this rate.
             * @example 120
             */
            driverPay?: number;
            /**
             * @description Helper pay for this rate.
             * @example 60
             */
            helperPay?: number;
            /**
             * Format: date-time
             * @description When this rate becomes effective (defaults to now).
             */
            effectiveFrom?: string;
            /**
             * Format: date-time
             * @description When this rate stops being effective (null = open-ended).
             */
            effectiveTo?: string;
        };
        TruckDaySummaryDto: {
            truckId: string;
            truckCode: string;
            /** @enum {string} */
            status: "none" | "draft" | "confirmed";
            /** @description Log id when one exists, else null. */
            logId?: Record<string, never> | null;
            /** @description Trips recorded for this truck that day. */
            tripCount: number;
        };
        OperationsSummaryCountsDto: {
            /** @description Active trucks considered. */
            trucks: number;
            none: number;
            draft: number;
            confirmed: number;
        };
        OperationsSummaryResponseDto: {
            /** Format: date */
            date: string;
            trucks: components["schemas"]["TruckDaySummaryDto"][];
            counts: components["schemas"]["OperationsSummaryCountsDto"];
        };
        DailyLogTotalsDto: {
            /** @description Financial — absent for ops roles. */
            billAmount: string;
            /** @description Financial — absent for ops roles. */
            driverPay: string;
            /** @description Financial — absent for ops roles. */
            helperPay: string;
        };
        TripResponseDto: {
            id: string;
            dailyLogId: string;
            /** @description Sequence within the log (1-based). */
            seq: number;
            clientId: string;
            routeLabel?: Record<string, never> | null;
            /** @description Financial — absent for ops roles. */
            billAmount: string;
            driverWorkerId: string;
            helperWorkerId?: Record<string, never> | null;
            /** @description Financial — absent for ops roles. */
            driverPay: string;
            /** @description Financial — absent for ops roles. */
            helperPay: string;
            rateId?: Record<string, never> | null;
            createdById?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DailyLogDetailResponseDto: {
            id: string;
            /** Format: date */
            date: string;
            truckId: string;
            /** @description Financial — absent for ops roles. */
            fuelCost?: Record<string, never> | null;
            odometerStart?: Record<string, never> | null;
            odometerEnd?: Record<string, never> | null;
            notes?: Record<string, never> | null;
            /** @enum {string} */
            status: "draft" | "confirmed";
            enteredById?: Record<string, never> | null;
            /** @description Number of trips under this log. */
            tripCount: number;
            totals: components["schemas"]["DailyLogTotalsDto"];
            /** @description Non-blocking validation warnings (odometer/empty-confirm). */
            warnings: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            trips: components["schemas"]["TripResponseDto"][];
        };
        CreateDailyLogDto: {
            /**
             * Format: date
             * @description Calendar date of the log. Unique together with truckId.
             * @example 2026-06-12
             */
            date: string;
            /** @description Truck this log belongs to. */
            truckId: string;
            /**
             * @description Fuel cost for the day (financial — stripped for ops roles).
             * @example 45
             */
            fuelCost?: number;
            /** @example 120000 */
            odometerStart?: number;
            /** @example 120140 */
            odometerEnd?: number;
            notes?: string;
        };
        DailyLogResponseDto: {
            id: string;
            /** Format: date */
            date: string;
            truckId: string;
            /** @description Financial — absent for ops roles. */
            fuelCost?: Record<string, never> | null;
            odometerStart?: Record<string, never> | null;
            odometerEnd?: Record<string, never> | null;
            notes?: Record<string, never> | null;
            /** @enum {string} */
            status: "draft" | "confirmed";
            enteredById?: Record<string, never> | null;
            /** @description Number of trips under this log. */
            tripCount: number;
            totals: components["schemas"]["DailyLogTotalsDto"];
            /** @description Non-blocking validation warnings (odometer/empty-confirm). */
            warnings: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateDailyLogDto: {
            /** @description Fuel cost (financial — stripped for ops roles). */
            fuelCost?: number;
            odometerStart?: number;
            odometerEnd?: number;
            notes?: string;
        };
        CreateTripDto: {
            /** @description Client billed for this trip. */
            clientId: string;
            /** @example Ciudad → Colón */
            routeLabel?: string;
            /** @description Driver (Worker) for the trip. */
            driverWorkerId: string;
            /** @description Optional helper (Worker). */
            helperWorkerId?: string;
            /** @description Charge to the client. Overrides the rate when given; defaults from the effective rate, else 0. */
            billAmount?: number;
            /** @description Driver pay. Overrides the rate when given. */
            driverPay?: number;
            /** @description Helper pay. Overrides the rate when given. */
            helperPay?: number;
            /** @description Explicit rate to apply. When omitted, the effective rate is resolved from clientId + routeLabel. */
            rateId?: string;
        };
        UpdateTripDto: {
            /** @description Client billed for this trip. */
            clientId?: string;
            /** @example Ciudad → Colón */
            routeLabel?: string;
            /** @description Driver (Worker) for the trip. */
            driverWorkerId?: string;
            /** @description Optional helper (Worker). */
            helperWorkerId?: string;
            /** @description Charge to the client. Overrides the rate when given; defaults from the effective rate, else 0. */
            billAmount?: number;
            /** @description Driver pay. Overrides the rate when given. */
            driverPay?: number;
            /** @description Helper pay. Overrides the rate when given. */
            helperPay?: number;
            /** @description Explicit rate to apply. When omitted, the effective rate is resolved from clientId + routeLabel. */
            rateId?: string;
        };
        DayTripCountDto: {
            /**
             * Format: date
             * @example 2026-06-12
             */
            date: string;
            /** @example 7 */
            tripCount: number;
        };
        TruckTripCountDto: {
            truckId: string;
            /** @example Camión 7 */
            truckCode: string;
            /** @example 12 */
            tripCount: number;
        };
        TripsReportResponseDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @description Total trips in the range. */
            totalTrips: number;
            perDay: components["schemas"]["DayTripCountDto"][];
            perTruck: components["schemas"]["TruckTripCountDto"][];
        };
        DayUtilizationDto: {
            /**
             * Format: date
             * @example 2026-06-12
             */
            date: string;
            /** @description Active trucks in the fleet (current status). */
            activeTrucks: number;
            /** @description Distinct active trucks with ≥1 trip that day. */
            trucksWithTrips: number;
            /**
             * @description trucksWithTrips ÷ activeTrucks (0..1, 4-dp). 0 if no trucks.
             * @example 0.75
             */
            utilization: number;
        };
        UtilizationReportResponseDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            perDay: components["schemas"]["DayUtilizationDto"][];
        };
        WorkerPayDto: {
            workerId: string;
            workerName: string;
            /** @description Sum of driverPay on trips driven (financial). */
            driverPay: string;
            /** @description Sum of helperPay on trips helped (financial). */
            helperPay: string;
            /** @description driverPay + helperPay (financial). */
            totalPay: string;
        };
        WorkerPayReportResponseDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            workers: components["schemas"]["WorkerPayDto"][];
        };
        ClientBillableDto: {
            clientId: string;
            clientName: string;
            /** @description Trips billed to this client in the range. */
            tripCount: number;
            /** @description Sum of billAmount (financial). */
            billAmount: string;
        };
        ClientBillablesReportResponseDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            clients: components["schemas"]["ClientBillableDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description Refresh cookie missing, invalid, or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_setRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FleetController_list: {
        parameters: {
            query?: {
                /** @description Filter by status (omit for all). */
                status?: "active" | "inactive";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FleetController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTruckDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FleetController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FleetController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTruckDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FleetController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkforceController_list: {
        parameters: {
            query?: {
                /** @description Filter by status. */
                status?: "active" | "disabled";
                /** @description Filter by type. */
                type?: "employee" | "contractor";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkforceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkforceController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkforceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkforceController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_list: {
        parameters: {
            query?: {
                /** @description Filter by status. */
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_listRateCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_createRateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRateCardDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_getRateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_updateRateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRateCardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_deactivateRateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_listRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"][];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_createRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_lookup: {
        parameters: {
            query: {
                /** @description Client whose effective rate is requested. */
                clientId: string;
                /** @description Optional route/service label to match exactly. Omit to match rates regardless of label. */
                label?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLookupResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_updateRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_closeRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_summary: {
        parameters: {
            query: {
                /** @description Date to summarize per-truck log status for. */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsSummaryResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_getLog: {
        parameters: {
            query: {
                date: string;
                truckId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogDetailResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_createLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDailyLogDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_getLogById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogDetailResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_updateLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDailyLogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_confirmLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationsController_updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingController_trips: {
        parameters: {
            query?: {
                /** @description Inclusive start date. Defaults to (to − 29 days). */
                from?: string;
                /** @description Inclusive end date. Defaults to today (UTC). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripsReportResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingController_utilization: {
        parameters: {
            query?: {
                /** @description Inclusive start date. Defaults to (to − 29 days). */
                from?: string;
                /** @description Inclusive end date. Defaults to today (UTC). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilizationReportResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingController_workerPay: {
        parameters: {
            query?: {
                /** @description Inclusive start date. Defaults to (to − 29 days). */
                from?: string;
                /** @description Inclusive end date. Defaults to today (UTC). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPayReportResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingController_clientBillables: {
        parameters: {
            query?: {
                /** @description Inclusive start date. Defaults to (to − 29 days). */
                from?: string;
                /** @description Inclusive end date. Defaults to today (UTC). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBillablesReportResponseDto"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
